### ISSUE TITLE
"Face Sprites" script variable does nothing(?)

### ISSUE THREAD

**Issue by Rouji** [brunosxs/SMRT-Godot#1]
Hi!

I'm fairly new to Godot, so this could well be a PEBKAC, but I can't get the "Face Sprites" variable to work. Anything I put in there simply gets ignored and frames from the built-in AnimatedSprite "face" are displayed.

If I go in and change that "face" node inside of the dialog, that of course then works, but I don't think that's how I'm supposed to do this.

Any thoughts?

**Comment by brunosxs** [comment]
Hi @Rj48 ,  this is a normal behavior as it is the defaults in case it doesn't get a valid spriteFrames object.

the dialog system uses vars that are exported and can be changed through the editor inspector itself as I planned to keep it as integrated to the editor as my skills could make it possible.

![configure_it](https://cloud.githubusercontent.com/assets/1557903/17839233/3945d81e-67b8-11e6-8b15-b79573fad82b.png)
Take note that there's a little arrow for each variable present under the Script Variable session. It is there that you should make changes.

Have a look at the GettingStarted article on the wiki of the project to have a clear understanding of this and the other possible personalizations. 

Also, since you're new, I'd suggest you to look at the export command at [GDScript article at the docs](http://docs.godotengine.org/en/latest/reference/gdscript.html) and this [question on the QA with the list of possible exported hints](https://godotengine.org/qa/6099/list-of-export-hints)

**Comment by Rouji** [comment]
Yes, I've read the Wiki page, and I'm well aware of the exported variables, but that's exactly what I can't get to work.
If I put a .tres containing a SpriteFrames object in there (i.e. clicking the arrow -> edit -> putting in an image -> save), it does not work.

Also, a quick grep -r doesn't show the face_sprites export ever being accessed anywhere, apart from a single "face_sprites = null" assignment in the SMRT/dialog.tscn (that just being its default value for new dialog nodes/scenes, I assume)

I'm not sure what I'm missing here, but it must be something really stupid and obvious^^;

**Comment by brunosxs** [comment]
Actually, I was the one who made a mistake and the script was an old version, before I had made the changes to make the items changeable through the editor.
Thanks for pointing it out, it should be working now. Waiting for your feedback.

**Comment by Rouji** [comment]
Works a treat, thanks!
