### ISSUE TITLE
Allow options to jump to another dialog and optionally a specific text.

### ISSUE THREAD

**Issue by Heybye44** [brunosxs/SMRT-Godot#4]

**Comment by brunosxs** [comment]
Not planned as it is already possible to do so with the signal `dialog_control`
[Read about it here](https://github.com/brunosxs/SMRT-Godot/wiki/Getting-Started#6-get-info-from-it)

Basically, through this signal, you can see in which part of the dialog you are, and start another dialog or even a single text.

**Comment by bobokox** [comment]
In some cases theres a problem if you want to start a new dialog directly from the `dialog_control` function or the `finished` function. you have to do it with a boolean in another function:
```
func _fixed_process(delta):
	if start:
		SMRT.show_text("chapter1", "dialog")
		start = false
	
	if next_dialog:
		SMRT.show_text("chapter2", "next_dialog")
		next_dialog = false

func _on_dialog_dialog_control( info ):
	if info.chapter == "chapter" && info.last_text_index == 3: next_dialog = true
```

**Comment by brunosxs** [comment]
Dunno if you have already done it, but there's a boolean that controls the flow of the dialog and can force-close it. 
`on_dialog`
Just set on_dialog to false when you get the signal, and then start the new dialog.

**Comment by nezvers** [comment]
This is the only major feature from a dialogue system that's not there. Have an option to add a connection to a different branch of dialogue (chapter, dialog, text).
Because now it's a must-have massive nested match or if net inside _on_dialogue_dialog_control for each chapter; dialog; last_text_index.
It would be great if answers could have a slot for a dictionary of desired dialogue and in dialog_control I could call it if such a thing isn't taken care of by the dialog system itself.
